apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "account.fullname" . }}
  labels:
    {{- include "account.labels" . | nindent 4 }}
data:
  config.yaml: | {{ toYaml .Values.account | nindent 4 }}
